distribution_code_name: "ibus-rime"
distribution_name: Rime
distribution_version: 1.2
install_time: "Mon Jan  2 23:24:21 2017"
installation_id: "2b7aa218-99b2-4e5a-9dd8-5c4e55536089"
rime_version: 1.2.9