var:
  option:
    simplification: true
  previously_selected_schema: luna_pinyin
  schema_access_time:
    bopomofo_tw: 1485141010
    luna_pinyin: 1487221152
    luna_pinyin_fluency: 1483378554
    luna_pinyin_simp: 1483378581
    "terra-pinyin": 1483675247
    terra_pinyin: 1483770950
    wubi86: 1483378392